Add PR template
Otus-DevOps-2018-02/Edmakas_microservices pull request #1
Opened 2018-03-06 15:27 UTC by Edmakas

Это pull request шаблон. Шаблон будет использован в следующих DZ.

2018-03-13 08:55 UTC, vitkhab requested changes
Оформи, пожалуйста, PR по шаблону

2018-03-16 05:48 UTC, Edmakas commented
# Выполнено ДЗ № 2

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - 
 - Добавлен шаблон PR
 - Создан PR
 - Запомнил PR по шаблону

## Как запустить проект:
 - Hе требуется - это лишь скелетон 

## Как проверить работоспособность:
 - Hе требуется -это лишь скелетон 

## PR checklisk
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-03-16 05:49 UTC, Edmakas commented
Нечаянно нажал на close

2018-06-18 13:17 UTC, Nklya commented
PR нужно было мержить, а не закрывать.
Теперь в мастере нет ни шаблона PR, ни .travis.yml

2018-06-18 13:18 UTC, merged